//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseCourse.Model1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class chineEntities : DbContext
    {
        public chineEntities()
            : base("name=chineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Role> Role { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<Task> Task { get; set; }
        public DbSet<TaskAndTheory> TaskAndTheory { get; set; }
        public DbSet<Theory> Theory { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<UserAndTask> UserAndTask { get; set; }
    }
}
