//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseCourse.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.UserAndTask = new HashSet<UserAndTask>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<UserAndTask> UserAndTask { get; set; }
    }
}
