//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseCourse.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theory
    {
        public Theory()
        {
            this.TaskAndTheory = new HashSet<TaskAndTheory>();
        }
    
        public int id { get; set; }
        public string Symbol { get; set; }
        public string Discription { get; set; }
        public string Photo { get; set; }
    
        public virtual ICollection<TaskAndTheory> TaskAndTheory { get; set; }
    }
}
