//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseCourse.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAndTask
    {
        public int id { get; set; }
        public int idUser { get; set; }
        public int idTask { get; set; }
        public int idStatus { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
    }
}
